---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: ./

      - name: Lint markdown files
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: './'

      - name: Run JSON Lint
        env:
          SHOW_ERRORS: true
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm install
        working-directory: src/auth-form

      - name: Install ESLint
        run: npm install eslint -DE
        working-directory: src/auth-form

      - name: Code Linting
        run: npm run lint
        working-directory: src/auth-form
